// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kgs/internal/biz"
	"kgs/internal/conf"
	"kgs/internal/data"
	"kgs/internal/server"
	"kgs/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	kgsRepo := data.NewKGSRepo(dataData, logger)
	kgsUsecase := biz.NewKGSUsecase(kgsRepo, logger)
	kgsService := service.NewKGSService(kgsUsecase)
	grpcServer := server.NewGRPCServer(confServer, kgsService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
